services:
  postgres:
    image: postgres:14
    container_name: graph-postgres
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    ports:
      - "5432:5432"

  ipfs:
    image: ipfs/kubo:v0.26.0
    container_name: graph-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"

  graph-node:
    image: graphprotocol/graph-node:v0.36.0
    container_name: graph-node
    depends_on:
      - postgres
      - ipfs
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: letmein
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ipfs_gateway: "ipfs:8080"
      ethereum: "hardhat:http://host.docker.internal:8545"
      GRAPH_LOG: info
    extra_hosts:
      - "host.docker.internal:host-gateway"